#!/usr/bin/env bash

## OS/ENVIRONMENT INFO DETECTION

kernel="$(uname -r)"
host="$(hostname)"
case $OSTYPE in
	"linux-gnu"*)
		. /etc/os-release
		os=$PRETTY_NAME
		shell=${SHELL##*/};;
	"darwin"*)
		while IFS='<>' read -r _ _ line _; do
			case $line in
				ProductVersion)
					IFS='<>' read -r _ _ mac_version _
					break;;
			esac
		done < /System/Library/CoreServices/SystemVersion.plist
		os="macOS ${mac_version}";;
	*) os="Idk"
esac

## PACKAGE MANAGER AND PACKAGES DETECTION

manager=$(command which nix-env yum dnf rpm xbps-query apt brew port zypper pacman apk cpm)
manager=${manager##*/}
case $manager in
	cpm) packages="$(cpm C)";;
	brew) packages="$(brew list | wc -l)";;
	port) packages=$(($(port installed | wc -l)-1));;
	apt) packages="$(dpkg-query -f '${binary:Package}\n' -W | wc -l)";;
	rpm) packages="$(rpm -qa --last| wc -l)";;
	yum) packages="$(yum list installed | wc -l)";;
	dnf) packages="$(dnf list installed | wc -l)";;
	zypper) packages="$(zypper se | wc -l)";;
	pacman) packages="$(pacman -Q | wc -l)";;
	xbps-query) packages="$(xbps-query -l | wc -l)";;
	nix-env) packages="$(nix-store -q --requisites /run/current-system/sw | wc -l)";;
	apk) packages="$(apk list --installed | wc -l)";;
	*) packages="idk"
esac

## UPTIME DETECTION

case $OSTYPE in
	"linux-gnu"*) IFS=. read -r s _ < /proc/uptime;;
	*) 
		s=$(sysctl -n kern.boottime)
		s=${s#*=}
		s=${s%,*}
		s=$(($(date +%s) - s));;
esac
d="$((s / 60 / 60 / 24))"
h="$((s / 60 / 60 % 24))"
m="$((s / 60 % 60))"
# Plurals
[ "$d" -gt 1 ] && dp=s
[ "$h" -gt 1 ] && hp=s
[ "$m" -gt 1 ] && mp=s
# Hide empty fields.
[ "$d" = 0 ] && d=
[ "$h" = 0 ] && h=
[ "$m" = 0 ] && m=
# Make the output of uptime smaller.
case $uptime_shorthand in
	tiny)
		[ "$d" ] && uptime="${d}d, "
		[ "$h" ] && uptime="$uptime${h}h, "
		[ "$m" ] && uptime="$uptime${m}m"
		uptime=${uptime%, };;
	*)
		[ "$d" ] && uptime="$d day$dp, "
		[ "$h" ] && uptime="$uptime$h hour$hp, "
		[ "$m" ] && uptime="$uptime$m min$mp"
		uptime=${uptime%, };;
esac

## RAM DETECTION

case $OSTYPE in
	"linux-gnu"*)
		while IFS=':k '  read -r key val _; do
			case $key in
				MemTotal)
					mem_used=$((mem_used + val))
					mem_full=$val;;
				Shmem) mem_used=$((mem_used + val));;
				MemFree|Buffers|Cached|SReclaimable) mem_used=$((mem_used - val));;
			esac
		done < /proc/meminfo
		mem_used=$((mem_used / 1024)) 
		mem_full=$((mem_full / 1024));;
	"darwin"*)
		mem_full=$(($(sysctl -n hw.memsize) / 1024 / 1024))
		while IFS=:. read -r key val; do
			case $key in
				*' wired'*|*' active'*|*' occupied'*)
					mem_used=$((mem_used + ${val:-0}));;
			esac
			done <<-EOF
				$(vm_stat)
						EOF

			mem_used=$((mem_used * 4 / 1024));;
	*)
		mem_full="idk"
		mem_used="idk"
esac
memstat="${mem_used}/${mem_full} MB"
mempercent="$("scale=2; ${mem_used}/${mem_full}" | bc -l )"
mempercent="echo $mempercent | cut -c2-"

## DEFINE COLORS

bold=$'\033[1m'
black=$'\033[30m'
red=$'\033[31m'
green=$'\033[32m'
yellow=$'\033[33m'
blue=$'\033[34m'
magenta=$'\033[35m'
cyan=$'\033[36m'
white=$'\033[37m'
reset=$'\033[0m'

## USER VARIABLES -- YOU CAN CHANGE THESE

lc="${reset}${bold}${magenta}"  # labels
nc="${reset}${bold}${yellow}"   # user
hn="${reset}${bold}${blue}"     # hostname
ic="${reset}${green}"           # info
c0="${reset}${black}"           # first color
c1="${reset}${white}"           # second color
c2="${reset}${yellow}"          # third color

## OUTPUT

cat <<EOF

${c0}      ___     ${nc}${USER}${red}@${reset}${hn}${host}${reset} 
${c0}     (${c1}.. ${c0}\    ${lc}  ${ic}${os}${reset}
${c0}     (${c2}<> ${c0}|    ${lc}  ${ic}${kernel}${reset}
${c0}    /${c1}/  \\ ${c0}\\   ${lc}  ${ic}${RAM}${memstat} (${mempercent}%)
${c0}   ( ${c1}|  | ${c0}/|  ${lc}  ${ic}${packages} (${manager})${reset}
${c2}  _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})  ${lc}  ${ic}${uptime}${reset}
${c2}  \/${c0}-____${c2}\/${reset}   ${black}███${red}███${green}███${yellow}███${blue}███${magenta}███${cyan}███${reset}
EOF
